In [18]:

import numpy as np
#Creating array object
arr = np.array( [[ 1, 2, 3],[ 4, 2, 5]] )
# Printing type of arr object
print("Array is of type: ", type(arr))
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
# Printing shape of array
print("Shape of array: ", arr.shape)
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)


Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


In [21]:
# Creating array from tuple
b = np.array((1 , 3, 2))
print ("\nArray created using passed tuple:\n", b)
# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)
# Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()
print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)
# Create a 3x3 identity matrix
I = np.identity(3)
print(I)

# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],[5,5,6,7],[1,5,7,8]])
newarr = arr.reshape(2, 2, 3)
print ("\nOriginal array:\n", arr)
print ("Reshaped array:\n", newarr)


Array created using passed tuple:
 [1 3 2]

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Original array:
 [[1 2 3 4]
 [5 5 6 7]
 [1 5 7 8]]
Reshaped array:
 [[[1 2 3]
  [4 5 5]]

 [[6 7 1]
  [5 7 8]]]


In [17]:
 #Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])

flarr = arr.flatten()
print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)
# Create a 3x3 identity matrix
I = np.identity(3)
print(I)

[[[1 2 3]
  [4 5 6]]]

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
